# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestHzx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FlexLib', :git => 'https://github.com/hzx157/FlexLib.git'


  # Pods for TestHzx

end
